// NEXUS ENTERPRISE DATABASE - ISO 27001:2022 (All 93 Controls)
export const BASE_STANDARDS = [
  // --- SECTION 5: ORGANIZATIONAL CONTROLS ---
  { id: 'ISO_5_1', name: '5.1 Policies for info security', group: 1, remediation: 'Draft and publish a master InfoSec policy. Ensure it is approved by executive management and acknowledged by all staff.' },
  { id: 'ISO_5_2', name: '5.2 Info security roles', group: 1, remediation: 'Publish an organizational chart defining CISO, Data Protection Officer, and Incident Response roles.' },
  { id: 'ISO_5_3', name: '5.3 Segregation of duties', group: 1, remediation: 'Separate conflicting duties (e.g., developers cannot deploy directly to production) to reduce risk of fraud or accidental errors.' },
  { id: 'ISO_5_4', name: '5.4 Management responsibilities', group: 1, remediation: 'Mandate quarterly executive reviews of the ISMS and track management participation in security steering committees.' },
  { id: 'ISO_5_5', name: '5.5 Contact with authorities', group: 1, remediation: 'Maintain a documented list of contacts for local law enforcement, regulatory bodies (e.g., ICO for GDPR), and ISPs.' },
  { id: 'ISO_5_6', name: '5.6 Contact with special interest groups', group: 1, remediation: 'Maintain memberships in cybersecurity forums (e.g., ISACA, OWASP) to stay updated on emerging threat intelligence.' },
  { id: 'ISO_5_7', name: '5.7 Threat intelligence', group: 1, remediation: 'Subscribe to automated threat intelligence feeds and integrate them into your SIEM.' },
  { id: 'ISO_5_8', name: '5.8 Info security in project management', group: 1, remediation: 'Integrate security gates into all Agile/Scrum project management lifecycles.' },
  { id: 'ISO_5_9', name: '5.9 Inventory of information and assets', group: 1, remediation: 'Deploy an automated IT Asset Management (ITAM) tool to track all hardware, software, and data repositories.' },
  { id: 'ISO_5_10', name: '5.10 Acceptable use of assets', group: 1, remediation: 'Require all employees to sign an Acceptable Use Policy (AUP) before receiving corporate devices.' },
  { id: 'ISO_5_11', name: '5.11 Return of assets', group: 1, remediation: 'Implement an automated HR offboarding checklist that revokes access and requires physical device return within 24 hours.' },
  { id: 'ISO_5_12', name: '5.12 Classification of information', group: 1, remediation: 'Define a 4-tier data classification scheme (Public, Internal, Confidential, Restricted).' },
  { id: 'ISO_5_13', name: '5.13 Labelling of information', group: 1, remediation: 'Enforce automated document tagging and email subject labelling (e.g., [CONFIDENTIAL]) using DLP software.' },
  { id: 'ISO_5_14', name: '5.14 Information transfer', group: 1, remediation: 'Mandate TLS 1.2+ for all data in transit and ban the use of unencrypted USB drives or personal file-sharing apps.' },
  { id: 'ISO_5_15', name: '5.15 Access control', group: 1, remediation: 'Implement Role-Based Access Control (RBAC) linked to the central HR directory.' },
  { id: 'ISO_5_16', name: '5.16 Identity management', group: 1, remediation: 'Deploy a centralized IAM provider (e.g., Okta, Entra ID) to govern all user identities lifecycle.' },
  { id: 'ISO_5_17', name: '5.17 Authentication information', group: 1, remediation: 'Enforce a minimum 12-character passphrase policy and prohibit password reuse.' },
  { id: 'ISO_5_18', name: '5.18 Access rights', group: 1, remediation: 'Conduct a quarterly User Access Review (UAR) to ensure standard users do not possess administrative privileges.' },
  { id: 'ISO_5_19', name: '5.19 Info security in supplier relationships', group: 1, remediation: 'Implement a Vendor Risk Management (VRM) program requiring SOC 2 reports from all third-party SaaS providers.' },
  { id: 'ISO_5_20', name: '5.20 Addressing security in supplier agreements', group: 1, remediation: 'Add mandatory "Right to Audit" and "Breach Notification" clauses to all third-party contracts.' },
  { id: 'ISO_5_21', name: '5.21 Managing info security in the ICT supply chain', group: 1, remediation: 'Require Software Bill of Materials (SBOM) from vendors to track vulnerabilities in third-party code.' },
  { id: 'ISO_5_22', name: '5.22 Monitoring, review and change management of supplier services', group: 1, remediation: 'Establish an annual SLA review meeting with critical cloud providers (AWS, Azure, GCP).' },
  { id: 'ISO_5_23', name: '5.23 Info security for use of cloud services', group: 1, remediation: 'Deploy a Cloud Access Security Broker (CASB) to monitor and govern unauthorized shadow IT.' },
  { id: 'ISO_5_24', name: '5.24 Info security incident management planning', group: 1, remediation: 'Draft an Incident Response Plan (IRP) defining severities, escalation matrices, and containment procedures.' },
  { id: 'ISO_5_25', name: '5.25 Assessment and decision on info security events', group: 1, remediation: 'Define a triage process to classify events as false positives, minor events, or critical breaches within 1 hour.' },
  { id: 'ISO_5_26', name: '5.26 Response to info security incidents', group: 1, remediation: 'Establish a 24/7 Security Operations Center (SOC) capability or retain a third-party IR firm.' },
  { id: 'ISO_5_27', name: '5.27 Learning from info security incidents', group: 1, remediation: 'Conduct mandatory "Post-Mortem" root-cause analysis meetings within 72 hours of incident resolution.' },
  { id: 'ISO_5_28', name: '5.28 Collection of evidence', group: 1, remediation: 'Establish digital forensics procedures (e.g., creating write-blocked disk images) to preserve chain of custody.' },
  { id: 'ISO_5_29', name: '5.29 Info security during disruption', group: 1, remediation: 'Maintain offline backups of critical cryptographic keys and configurations required to rebuild the network.' },
  { id: 'ISO_5_30', name: '5.30 ICT readiness for business continuity', group: 1, remediation: 'Deploy redundant, geographically separated server architectures with automated failover testing.' },
  { id: 'ISO_5_31', name: '5.31 Legal, statutory, regulatory requirements', group: 1, remediation: 'Maintain a compliance matrix mapping internal policies to GDPR, CCPA, and industry-specific regulations.' },
  { id: 'ISO_5_32', name: '5.32 Intellectual property rights', group: 1, remediation: 'Enforce software licensing audits and prohibit the installation of unapproved open-source or pirated software.' },
  { id: 'ISO_5_33', name: '5.33 Protection of records', group: 1, remediation: 'Define a data retention and secure destruction schedule. Retain audit logs for a minimum of 365 days.' },
  { id: 'ISO_5_34', name: '5.34 Privacy and protection of PII', group: 1, remediation: 'Implement Data Loss Prevention (DLP) to block the unauthorized exfiltration of credit cards and social security numbers.' },
  { id: 'ISO_5_35', name: '5.35 Independent review of info security', group: 1, remediation: 'Contract a certified third-party auditing firm to conduct an annual external ISO 27001 surveillance audit.' },
  { id: 'ISO_5_36', name: '5.36 Compliance with policies', group: 1, remediation: 'Automate compliance checks using Cloud Security Posture Management (CSPM) tools.' },
  { id: 'ISO_5_37', name: '5.37 Documented operating procedures', group: 1, remediation: 'Maintain a centralized wiki (e.g., Confluence) containing step-by-step IT runbooks and disaster recovery guides.' },

  // --- SECTION 6: PEOPLE CONTROLS ---
  { id: 'ISO_6_1', name: '6.1 Screening', group: 1, remediation: 'Require criminal background checks and reference verification for all new hires handling sensitive data.' },
  { id: 'ISO_6_2', name: '6.2 Terms and conditions of employment', group: 1, remediation: 'Embed Non-Disclosure Agreements (NDAs) and confidentiality clauses directly into standard employment contracts.' },
  { id: 'ISO_6_3', name: '6.3 Info security awareness, education', group: 1, remediation: 'Mandate bi-annual security awareness training covering phishing, social engineering, and password hygiene.' },
  { id: 'ISO_6_4', name: '6.4 Disciplinary process', group: 1, remediation: 'Publish a clear HR disciplinary matrix outlining consequences for violating data security policies.' },
  { id: 'ISO_6_5', name: '6.5 Responsibilities after termination', group: 1, remediation: 'Remind offboarded employees of their surviving confidentiality obligations in writing during exit interviews.' },
  { id: 'ISO_6_6', name: '6.6 Confidentiality or non-disclosure agreements', group: 1, remediation: 'Require signed NDAs from all contractors, guests, and third-party vendors before granting facility or network access.' },
  { id: 'ISO_6_7', name: '6.7 Remote working', group: 1, remediation: 'Mandate the use of corporate VPNs and restrict the downloading of sensitive data to unmanaged personal devices.' },
  { id: 'ISO_6_8', name: '6.8 Info security event reporting', group: 1, remediation: 'Deploy an anonymous "Security Hotline" or one-click email button for employees to report suspicious activities.' },

  // --- SECTION 7: PHYSICAL CONTROLS ---
  { id: 'ISO_7_1', name: '7.1 Physical security perimeters', group: 1, remediation: 'Implement badge-access doors, security guards, and turnstiles at all primary corporate entrances.' },
  { id: 'ISO_7_2', name: '7.2 Physical entry', group: 1, remediation: 'Maintain visitor logs and require guests to wear visible badges and be escorted at all times.' },
  { id: 'ISO_7_3', name: '7.3 Securing offices, rooms, facilities', group: 1, remediation: 'Install biometric scanners or specialized keycards for high-security areas like server rooms and HR filing archives.' },
  { id: 'ISO_7_4', name: '7.4 Physical security monitoring', group: 1, remediation: 'Deploy 24/7 CCTV surveillance covering all facility perimeters, server rooms, and primary corridors.' },
  { id: 'ISO_7_5', name: '7.5 Protecting against physical/environmental threats', group: 1, remediation: 'Install fire suppression systems (e.g., FM-200), raised floors, and redundant HVAC in all server rooms.' },
  { id: 'ISO_7_6', name: '7.6 Working in secure areas', group: 1, remediation: 'Prohibit unauthorized photography, mobile phone usage, or unsecured recording devices inside highly secure zones.' },
  { id: 'ISO_7_7', name: '7.7 Clear desk and clear screen', group: 1, remediation: 'Enforce an automated 5-minute screen lock GPO. Require employees to securely lock away paper documents overnight.' },
  { id: 'ISO_7_8', name: '7.8 Equipment siting and protection', group: 1, remediation: 'Position monitors so they cannot be viewed from public windows to prevent shoulder surfing.' },
  { id: 'ISO_7_9', name: '7.9 Security of assets off-premises', group: 1, remediation: 'Require full-disk encryption (BitLocker/FileVault) on all laptops and track them using mobile asset software.' },
  { id: 'ISO_7_10', name: '7.10 Storage media', group: 1, remediation: 'Store backup tapes in fireproof safes and maintain an encrypted chain of custody for offsite transport.' },
  { id: 'ISO_7_11', name: '7.11 Supporting utilities', group: 1, remediation: 'Deploy Uninterruptible Power Supplies (UPS) and backup diesel generators for all critical data center infrastructure.' },
  { id: 'ISO_7_12', name: '7.12 Cabling security', group: 1, remediation: 'Run network cables through secure conduits or above drop ceilings to prevent physical wiretapping or severing.' },
  { id: 'ISO_7_13', name: '7.13 Equipment maintenance', group: 1, remediation: 'Maintain active OEM support contracts for critical hardware. Wipe data from failed drives before returning them to vendors.' },
  { id: 'ISO_7_14', name: '7.14 Secure disposal or re-use of equipment', group: 1, remediation: 'Contract a certified e-waste vendor to physically shred hard drives and provide Certificates of Destruction.' },

  // --- SECTION 8: TECHNOLOGICAL CONTROLS ---
  { id: 'ISO_8_1', name: '8.1 User endpoint devices', group: 1, remediation: 'Deploy Mobile Device Management (MDM) to enforce security profiles and enable remote wipe capabilities.' },
  { id: 'ISO_8_2', name: '8.2 Privileged access rights', group: 1, remediation: 'Implement a Privileged Access Management (PAM) vault to rotate and audit administrator credentials.' },
  { id: 'ISO_8_3', name: '8.3 Info access restriction', group: 1, remediation: 'Enforce network segmentation and VLANs to isolate sensitive databases from standard user networks.' },
  { id: 'ISO_8_4', name: '8.4 Access to source code', group: 1, remediation: 'Restrict access to code repositories (e.g., GitHub/GitLab) using strict Branch Protection rules and MFA.' },
  { id: 'ISO_8_5', name: '8.5 Secure authentication', group: 1, remediation: 'Mandate hardware-backed Multi-Factor Authentication (MFA), such as YubiKeys or Authenticator Apps, across all systems.' },
  { id: 'ISO_8_6', name: '8.6 Capacity management', group: 1, remediation: 'Implement cloud auto-scaling groups and configure alerts for CPU/Storage utilization reaching 80%.' },
  { id: 'ISO_8_7', name: '8.7 Protection against malware', group: 1, remediation: 'Deploy Next-Generation Antivirus (NGAV) / EDR agents like CrowdStrike or SentinelOne to all endpoints.' },
  { id: 'ISO_8_8', name: '8.8 Management of technical vulnerabilities', group: 1, remediation: 'Conduct weekly automated vulnerability scans and enforce a 14-day SLA for patching critical CVEs.' },
  { id: 'ISO_8_9', name: '8.9 Configuration management', group: 1, remediation: 'Define secure baselines using CIS Benchmarks and use Infrastructure as Code (Terraform) to prevent drift.' },
  { id: 'ISO_8_10', name: '8.10 Information deletion', group: 1, remediation: 'Automate database scripts to purge or permanently anonymize user data upon customer request or account termination.' },
  { id: 'ISO_8_11', name: '8.11 Data masking', group: 1, remediation: 'Use dynamic data masking to obscure PII and credit card numbers from developers and support staff UIs.' },
  { id: 'ISO_8_12', name: '8.12 Data leakage prevention', group: 1, remediation: 'Deploy DLP agents to endpoints and email gateways to block the exfiltration of intellectual property.' },
  { id: 'ISO_8_13', name: '8.13 Information backup', group: 1, remediation: 'Implement a 3-2-1 backup strategy: 3 copies of data, across 2 different media, with 1 copy stored offline/immutable.' },
  { id: 'ISO_8_14', name: '8.14 Redundancy of info processing facilities', group: 1, remediation: 'Architect cloud applications across Multi-AZ (Availability Zones) to ensure continuous uptime during outages.' },
  { id: 'ISO_8_15', name: '8.15 Logging', group: 1, remediation: 'Forward all system, firewall, and application audit logs to a centralized, tamper-proof SIEM environment.' },
  { id: 'ISO_8_16', name: '8.16 Monitoring activities', group: 1, remediation: 'Configure SIEM rules to trigger automated alerts for impossible travel, multiple failed logins, and privilege escalation.' },
  { id: 'ISO_8_17', name: '8.17 Clock synchronization', group: 1, remediation: 'Configure all servers, endpoints, and firewalls to sync time via a secure, internal NTP (Network Time Protocol) server.' },
  { id: 'ISO_8_18', name: '8.18 Use of privileged utility programs', group: 1, remediation: 'Block standard users from executing command-line utilities (e.g., PowerShell, bash) via application whitelisting.' },
  { id: 'ISO_8_19', name: '8.19 Installation of software on operational systems', group: 1, remediation: 'Remove local admin rights to prevent users from installing unapproved or shadow IT applications.' },
  { id: 'ISO_8_20', name: '8.20 Network security', group: 1, remediation: 'Deploy Next-Generation Firewalls (NGFW) with intrusion prevention systems (IPS) and deep packet inspection.' },
  { id: 'ISO_8_21', name: '8.21 Security of network services', group: 1, remediation: 'Mandate zero-trust architectures; require explicit mutual TLS authentication for microservice-to-microservice communication.' },
  { id: 'ISO_8_22', name: '8.22 Segregation in networks', group: 1, remediation: 'Isolate guest Wi-Fi networks entirely from the corporate intranet using separate physical hardware or rigid VLAN tagging.' },
  { id: 'ISO_8_23', name: '8.23 Web filtering', group: 1, remediation: 'Implement DNS sinkholing and secure web gateways to block access to known malicious domains and inappropriate content.' },
  { id: 'ISO_8_24', name: '8.24 Use of cryptography', group: 1, remediation: 'Enforce AES-256 encryption for data at rest and deprecate all weak cipher suites (e.g., SSLv3, TLS 1.0).' },
  { id: 'ISO_8_25', name: '8.25 Secure development lifecycle', group: 1, remediation: 'Integrate SAST and DAST vulnerability scanning tools directly into the CI/CD pipeline.' },
  { id: 'ISO_8_26', name: '8.26 Application security requirements', group: 1, remediation: 'Include OWASP Top 10 mitigation requirements as acceptance criteria for all new software development tickets.' },
  { id: 'ISO_8_27', name: '8.27 Secure system architecture and engineering', group: 1, remediation: 'Adopt a "Security by Design" framework. Conduct threat modeling exercises before writing any code.' },
  { id: 'ISO_8_28', name: '8.28 Secure coding', group: 1, remediation: 'Provide annual secure coding training for developers and require mandatory peer reviews for all pull requests.' },
  { id: 'ISO_8_29', name: '8.29 Security testing in development', group: 1, remediation: 'Execute automated regression security tests and unit tests before any code is pushed to the staging environment.' },
  { id: 'ISO_8_30', name: '8.30 Outsourced development', group: 1, remediation: 'Require external development agencies to submit their code for independent security audits before acceptance.' },
  { id: 'ISO_8_31', name: '8.31 Separation of environments', group: 1, remediation: 'Ensure Dev, Staging, and Production environments reside in completely isolated VPCs with no cross-talk.' },
  { id: 'ISO_8_32', name: '8.32 Change management', group: 1, remediation: 'Establish a Change Advisory Board (CAB) to review and approve the security impact of all major production deployments.' },
  { id: 'ISO_8_33', name: '8.33 Test information', group: 1, remediation: 'Prohibit the use of real customer data in lower environments. Use synthetic data generators for QA testing.' },
  { id: 'ISO_8_34', name: '8.34 Protection of info systems during audit testing', group: 1, remediation: 'Ensure penetration tests and vulnerability scans are tightly scoped and scheduled during low-traffic maintenance windows.' }
];